# Generated by Django 3.2.9 on 2021-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='customers', to='backend.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='customers', to='backend.customers'),
        ),
    ]
