# Generated by Django 3.2.9 on 2021-11-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211122_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service', to='backend.service'),
        ),
    ]
