# Generated by Django 3.2.9 on 2021-11-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_customers_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='service',
        ),
    ]
