# Generated by Django 3.2.9 on 2021-11-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211122_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='customer',
        ),
        migrations.AddField(
            model_name='customers',
            name='common',
            field=models.ManyToManyField(blank=True, related_name='commons', to='backend.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='common',
            field=models.ManyToManyField(blank=True, related_name='commons', to='backend.customers'),
        ),
    ]
