# Generated by Django 3.2.9 on 2021-11-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211122_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='common',
        ),
    ]
